# Site settings
title: ADS Fatec Mogi das Cruzes
email: ads2015-tarde@googlegroups.com
description: > # this means to ignore newlines until "baseurl:"
  Site para troca de informações entre os alunos da primeira 
  turma de 2015, do curso vespertino, de Análise e Desenvolvimento
  de Sistemas da FATEC de Mogi das Cruzes.
baseurl: "/ads2015.1" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: _evertonsilva
github_username:  EvertonSilva

# Build settings
name: Análise e Desenvolvimento de Sistemas
markdown: redcarpet
highlighter: pygments

